# Generated by Django 4.1.2 on 2022-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('FEMALE', 'F')], default='M', max_length=6),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('FEMALE', 'F')], default='M', max_length=6),
        ),
    ]
