# Generated by Django 4.1.2 on 2023-02-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classgrade',
            unique_together={('school', 'class_grade', 'section')},
        ),
    ]
