# Generated by Django 4.1.2 on 2023-02-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_classgrade_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
