# Generated by Django 4.1.2 on 2022-11-25 14:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_sex_alter_teacher_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
    ]
