# Generated by Django 4.1.2 on 2022-11-25 15:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_teacher_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_grade',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(9, 9), (10, 10), (11, 11), (12, 12)], max_length=2),
        ),
    ]
