# Generated by Django 4.1.2 on 2022-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_teacher_class_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=12)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
    ]
