# Generated by Django 4.1.2 on 2023-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
