# Generated by Django 4.1.2 on 2023-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_exam_created_alter_exam_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='incorrect_ans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='incorrect_ans_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
