# Generated by Django 4.1.2 on 2022-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sectionclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
