# Generated by Django 4.1.2 on 2022-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_sectionclass_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
    ]
