# Generated by Django 4.1.2 on 2022-11-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_sectionclass_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionclass',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
    ]
