# Generated by Django 4.1.2 on 2023-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_exam_choose_answer_alter_exam_fillblank_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='incorrect_ans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='incorrect_ans_num',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
