# Generated by Django 4.1.2 on 2023-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_score_incorrect_ans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='fillblank_answer',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='truefalse_answer',
        ),
        migrations.AddField(
            model_name='exam',
            name='ans',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
