# Generated by Django 4.1.2 on 2022-11-27 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_instagram_user_facebook_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='sub_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
