# Generated by Django 4.1.2 on 2023-06-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_exam_fillblank_answer_exam_truefalse_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='ans',
        ),
        migrations.AddField(
            model_name='exam',
            name='matching_answer',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='truefalse_answer',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
