# Generated by Django 4.1.2 on 2022-11-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_school_city_school_registered_school_sub_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='unique_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.exam')),
            ],
        ),
    ]
