# Generated by Django 4.1.2 on 2022-11-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_exam_unique_name_addanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='base.exam'),
        ),
    ]
