# Generated by Django 4.1.2 on 2023-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_exam_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
