# Generated by Django 4.1.2 on 2023-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_exam_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.IntegerField(unique=True),
        ),
    ]
