# Generated by Django 4.1.2 on 2023-07-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_exam_exam_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_code',
        ),
    ]
