# Generated by Django 4.1.2 on 2022-12-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_exam_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
