# Generated by Django 4.1.2 on 2022-12-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_parent_school_name_remove_parent_user_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='student_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
