# Generated by Django 4.1.2 on 2023-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_exam_exam_code_b_alter_exam_exam_code_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code_b',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code_f',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
