# Generated by Django 4.1.2 on 2022-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_score_checked_by_score_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='unique_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
