# Generated by Django 4.1.2 on 2023-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_exam_exam_code_b_alter_exam_exam_code_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_exam_code_b',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_exam_code_f',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code_b',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code_f',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
