# Generated by Django 4.1.2 on 2022-12-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_exam_date_exam_choose_answer_exam_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions',
            new_name='no_of_questions',
        ),
    ]
