# Generated by Django 4.1.2 on 2023-07-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_score_score_exam_code_b_score_score_exam_code_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_exam_code_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_exam_code_f',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
