# Generated by Django 4.1.2 on 2022-12-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_questions_exam_no_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
    ]
