# Generated by Django 4.2.3 on 2023-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_score_score_exam_code_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
