# Generated by Django 4.1.2 on 2022-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_exam_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='no_of_questions',
            field=models.IntegerField(),
        ),
    ]
