# Generated by Django 4.1.2 on 2022-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_exam_no_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='choose_answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fillblank_answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='exam',
            name='truefalse_answer',
            field=models.CharField(max_length=50),
        ),
    ]
