# Generated by Django 4.1.2 on 2022-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_exam_choose_answer_alter_exam_fillblank_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='all_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
