# Generated by Django 4.1.2 on 2022-12-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_exam_all_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='all_answer',
        ),
    ]
