# Generated by Django 4.1.2 on 2022-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_grade_section_remove_sectionclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
