# Generated by Django 4.1.2 on 2022-12-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_student_class_grade_alter_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
