# Generated by Django 4.1.2 on 2022-12-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
    ]
