# Generated by Django 4.1.2 on 2022-12-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
