# Generated by Django 4.1.2 on 2022-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_teacher_class_grade_alter_teacher_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_num',
            field=models.IntegerField(default=9112233445),
            preserve_default=False,
        ),
    ]
