# Generated by Django 4.1.2 on 2022-12-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_teacher_class_grade_alter_teacher_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='student_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to='base.student'),
        ),
    ]
