# Generated by Django 4.1.2 on 2022-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_exam_options_remove_school_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='choose_answer',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fillblank_answer',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='exam',
            name='truefalse_answer',
            field=models.CharField(max_length=500),
        ),
    ]
