# Generated by Django 4.1.2 on 2022-12-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_exam_options_teacher_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='student_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to='base.student'),
        ),
    ]
