# Generated by Django 4.1.2 on 2023-01-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_exam_choose_answer_alter_exam_fillblank_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='checked_by',
        ),
    ]
